### ISSUE TITLE
[CI] Accuracy TestもCIで実行する

### ISSUE THREAD

**Issue by ensan-hcl** [ensan-hcl/azooKey#201]
なんかこんな感じでできそう。パフォーマンステストの点だとazooKeyTests/にあった方が嬉しい側面もあるので、どこまでをPackage配下でやるべきかは考える必要があると思う。
```
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install gdown
        run: |
          pip install gdown

      - name: Download latest_dic.zip
        run: |
          gdown --id 1ImBsHiZILYBYno4L0xvb0RfdXPKzeV_D --output KanaKanjiConverterModule/Source/latest_dic.zip

      - name: Remove Source/Dictionary
        run: |
          rm -rf KanaKanjiConverterModule/Source/Dictionary

      - name: Extract latest_dic.zip
        run: |
          unzip KanaKanjiConverterModule/Source/latest_dic.zip -d KanaKanjiConverterModule/Source/

      - name: Build and Test
        run: swift test
```
